#!/bin/bash
# install-mura.sh
# ---------------
# mura installation
#
# by Jas Panesar
# c 2011 until I figure out a license ;)
# feel free to learn from this and hold me accountable as much as you paid me for this.
#
# I download the latest mura, and unzip it in a folder of your choice
# This file has been barely tested.. use at your own peril
#
# This file is likely using no best practices for shell scripting.
# Feel free to improve.
#
# REQUIREMENTS:
# - Must be run as root
#
# SETUP:
# - You must chmod +x install-mura prior to running
#
# USAGE:
# ./install-mura <directory>    - the directory doesn't have to exist beforehand
#
# ROADMAP:
# - I want this to create the mysql database while I'm at it so I can pass it in.
# - I want this to auto activate the Mura installation

# variables not used yet
#
# muraurl = "http://www.getmura.com/index.cfm/?LinkServID=62611A40-FAD0-94F4-54E16A8FC4614BD2&showMeta=0"
# murafile = "mura-latest.zip"

# debug no parameters being passed in (directory is required!)
if [ -z "$1" ]
then
  echo "Usage: install-mura <directory>"
  exit
fi

#first create the directory
        echo "-> CREATED DIRECTORY $1/ "
        mkdir $1
        echo "   .. done"

        echo "-> CHMOD 777 empty dir $1/ "
        chmod -R 777 $1
        echo "   .. done"

#next let's download the latest mura and unzip it in the install folder.  remember to clean up the zip file downloaded after

        cd $1
        echo "--> DOWNLOAD and UNZIP latest Mura CMS.."
        curl -s -L "http://www.getmura.com/index.cfm/?LinkServID=62611A40-FAD0-94F4-54E16A8FC4614BD2&showMeta=0" -o "mura-latest.zip" && unzip -q "mura-latest.zip"

        echo "    cleanup zip file"
       rm -fr mura-latest.zip

        echo "    .. done "

# move back up and chmod the directory
        cd ..

        echo "--> chmod 777 entire directory.."
        chmod -R 777 $1
